/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Certification } from './Certification.js';
export * as factories from './factories/index.js';
export { Certification__factory } from './factories/Certification__factory.js';